# Site settings
title: blog.fujianjin6471.com
email: fujianjin6471@yeah.net
description: > # this means to ignore newlines until "baseurl:"
    Write something really helpful to me, hope the same to others.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.fujianjin6471.com" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000"
github_username:  fujianjin6471

# Build settings
markdown: kramdown
